# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Environment, used in labels
# environment: development

# Define the app version
version: 0.1.0

# Azure settings
azure:
  tenant: ""
  subscription: ""
  user: ""
  resgroup: ""
  dns: ""
  pwd: ""
  zone: ""

image:
  # The image repository
  repository: to-be-overridden
  # The image tag, needs to be overridden
  tag: latest

# Define resources for your deployment. 
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 125Mi

# This is an example how secrets can be interpolated into your secrets file. A good practice
# is not to store your variables or secrets in the pipeline but to use an Azure Keyvault. Contact
# your ops friends...
# secrets:
#   this_is_very_secret: "this value will be overwritten by the pipeline"