apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
data:
  AZ_TENANT: ""
  AZ_SUBSCRIPTION: ""
  AZ_USER: ""
  AZ_PWD: ""
  AZ_RESGROUP: ""
  AZ_DNS: ""