apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "project.selector" . | indent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "project.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "project.name" . }}
    spec:
      containers:
        - name: {{ include "project.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "project.name" . }}
            - secretRef:
                name: {{ include "project.name" . }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
