apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
data:
  # Fill in your secret, e.g.:
  # ENV_VALUE: "some secret"
  # See the values file to get more info on how this works...