apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "project.selector" . | indent 4 }}
